apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: immolink.ir
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: immolink-clusterip-srv
              port:
                number: 8080